const dictionary = ["ABENDMUSIK", "ABENDMUSIKEN", "AFFENPINSCHER", "AFFENPINSCHERS", "ANSCHAUUNG", "ANSCHAUUNGEN", "APFELSTRUDEL", "APFELSTRUDELS", "AUF", "AUFGABE", "AUFGABEN" "AUFGABEN", "AUFGABES", "AUFGEHOBEN", "AUFHEBUNG", "AUFHEBUNGEN", "AUFS", "AUFWUCHS", "AUSDRUCKSTANZ", "AUSDRUCKSTANZE", "AUTOBAHN", "AUTOBAHNEN", "AUTOBAHNS", "BAUMKUCHEN", "BEREITSCHAFTSPOTENTIAL", "BEREITSCHAFTSPOTENTIALS", "BERGSCHRUND", "BERGSCHRUNDS", "BEWUSSTSEINSLAGE", "BEWUSSTSEINSLAGEN", "BIERWURST", "BIERWURSTS", "BILDUNGSROMAN", "BILDUNGSROMANE", "BISMARCK", "BISMARCKS", "BLITZKRIEG", "BLITZKRIEGS", "BLUTWURST", "BLUTWURSTS", "BONSPIEL", "BONSPIELS", "BRATWURST", "BRATWURSTS", "BRAUNSCHWEIGER", "BRAUNSCHWEIGERS", "BREMSSTRAHLUNG", "BREMSSTRAHLUNGS", "CAPELLMEISTER", "CAPELLMEISTERS", "CURRYWURST", "CURRYWURSTS", "DIRNDLS”, "DIRNDL”, "DOBERMAN", "DOBERMANN", "DOBERMANNS", "DOBERMANS", "DUMMKOPF", "DUMMKOPFS", "EDELWEISS", "EDELWEISSES", "EDELZWICKER", "ENTWICKLUNGSROMAN", "ENTWICKLUNGSROMANE", "ERSATZ", "FESTSCHRIFT", "FESTSCHRIFTEN", "FESTSCHRIFTS", "FLAMMKUCHEN", "FLUGEL", "FLUGELHORN", "FLUGELHORNS", "FLUGELMAN", "FLUGELMEN", "FLUGELS", "FRANKFORT", "FRANKFORTS", "FRANKFURT", "FRANKFURTER", "FRANKFURTS", "FREMD", "FREMDS", "FUHRER", "FUHRER[RINZIP", "FUHRERPRINZIPS", "FUHRERS", "GEBRAUCHSMUSIK", "GELANDESPRUNG", "GELANDESPRUNGS", "GEMEINSCHAFT", "GEMEINSCHAFTEN", "GEMEINSCHAFTSGEFUHL", "GEMEINSCHAFTSGEFUHLE", "GEMUTLICHKEIT", "GEMUTLICHKEITEN", "GESELLSCHAFT", "GESELLSCHAFTEN", "GESUNDHEIT", "GLOCKENSPIEL", "GLOCKENSPIELS", "GUGELHUPF", "GUGELHUPFS", "GUGLHUPF", "GUGLHUPFS", "HASENPFEFFER”, "HEILIGENSCHEIN", "HEILIGENSCHEINS", "HERRENVOLK", "HERRENVOLKS", "HONIGKUCHEN", "INFOBAHN", "INFOBAHNS", "JAEGERS”, "JAEGER”, "JAGDTERRIER", "JAGDTERRIERS", "JAGDWURST", "JAGDWURSTS", "JAGER”, "KAFFEEKLATSCH", "KAFFEEKLATSCHEN", "KAFFEEKLATSCHES", "KAPELLMEISTER", "KAPELLMEISTERS", "KATZBALGER", "KATZBALGERS", "KATZENJAMMER". "KATZENJAMMERS", "KINDERSPIEL", "KINDERSPIELS", "KIRSCHWASSER", "KIRSCHWASSERS", "KITSCH", "KITSCHES", "KLATSCH", "KLATSCHES", "KLETTERSCHUH", "KLETTERSCHUHE", "KNACKWURST", "KNACKWURSTS", "KNOCKWURST", "KNOCKWURSTS", "KOCHWURST", "KOCHWURSTS", "KRIEGSPIEL", "KRIEGSPIELS", "KRIEGSSPIEL", "KRIEGSSPIELS", "KUCHEN", "KUCHENS", "KUGELHOPF", "KUGELHOPS", "KULTURKAMPF", "KULTURKAMPFES", "KULTURKAMPFS", "KUMMERBUND", "KUMMERBUNDS", "LANDJAEGER”, "LANDJAGERS”, "LANDJAGER”, "LANDSKNECHT", "LANDSKNECHTS", "LEBKUCHEN", "LEBKUCHENHERZ", "LEBKUCHENHERZEN", "LEBKUCHENHERZES", "LEBKUCHENS", "LEHR", "LEHRJAHRE", "LEHRMAN", "LEHRMEN", "LEHRS", "LUFTMENSCH", "LUFTMENSCHEN", "MACHTPOLITIK", "MACHTPOLITIKS", "MEISTER", "MEISTERGENSANGE", "MEISTERGESANG", "MEISTERS", "METTWURST", "MOZARTKUGEL", "MOZARTKUGELN", "NACHSCHLAG", "NACHSCHLAGS", "PFEFFERKUCHEN", "PINSCHER", "PINSCHERS", "RAUSCHPFEIFE", "RAUSCHPFEIFEN", "REALPOLITIK", "REALPOLITIKER", "REALPOLITIKERS", "REALPOLITIKS", "REICHSLAND", "REICHSLANDS", "REICHSMARK", "REICHSMARKS", "ROTTWEILER", "SAUERBRATEN", "SAUERBRATENS", "SAUERKRAUT", "SAUERKRAUTS", "SCHADENFREUDE", "SCHADENFREUDES", "SCHAFKOPF", "SCHAFSKOPF", "SCHERENSCHNITTE", "SCHERENSCHNITTES", "SCHLIERE", "SCHLIEREN", "SCHLIERES", "SCHMALZ", "SCHMALZES", "SCHMALZIER", "SCHMALZIEST", "SCHMALZY", "SCHNAPPER", "SCHNAPPERS", "SCHNAPPS", "SCHNAPPSES", "SCHNAPS", "SCHNAPSES", "SCHNAUZER", "SCHNAUZERS", "SCHNITZEL", "SCHNITZELS", "SCHREKLICH", "SCHROD", "SCHRODS", "SCHUETZENFEST", "SCHUETZENFESTE", "SCHUETZENFESTS", "SCHUHPLATTLER", "SCHUHPLATTLERS", "SCHUPFNUDEL", "SCHUPFNUDELN", "SCHUSS", "SCHUSSES", "SCHUTZENFEST", "SCHUTZENFESTE", "SCHUTZENFESTS", "SCHUTZHUND", "SCHWARMEREI", "SCHWARMERISCH", "SCHWARTZ", "SCHWARTZE", "SCHWARZBIER",  "SCHWARZBIERS", "SINGSPIEL", "SINGSPIELE", "SINGSPIELS", "SITZKRIEG", "SITZKRIEGS", "SPAETZLES”, "SPAETZLE”, "SPATZLES”, "SPATZLE”, "SPINNBARKEIT", "SPINNBARKEITS", "SPITZ", "SPITZENBERG", "SPITZENBERGS", "SPITZENBURG", "SPITZES", "STAHLHELM", "STAHLHELME", "STAHLHELMS", "STRUDEL", "STRUDELS", "TANZTHEATER", "UMWELT", "UMWELTEN", "UNTERMENSCH", "UNTERMENSCHEN", "VERFREMDUNGSEFFEKT", "VERFREMDUNGSEFFEKTE", "VOLK", "VOLKS", "VOLKSGEIST", "VOLKSGEISTER", "VOLKSGEMEINSCHAFT", "VOLKSGEMEINSCHAFTEN", "VOLKSLIEDER", "VOLKSLIEDERS", "WALPURGISNACHT", "WALPURGISNACHTE", "WEHRLITE", "WEHRLITES", "WEIHNACHTSMARKT", "WEIHNACHTSMARKTE", "WEIMARANER", "WEIMARANERS", "WEISE", "WEISED", "WEISEMHEIMERS", "WEISENHEIMER", "WEISES", "WEISSWURST", "WELTANSCHAUUNG", "WELTANSCHAUUNGEN", "WELTSCHMERZ", "WELTSCHMERZEN", "WELTSCHMERZES", "WIENERWURST", "WISSENSCHAFT",   "WUNDER", "WUNDERKAMMER", "WUNDERKAMMERN", "WUNDERKIND", "WUNDERKINDER", "WUNDERKINDS", "WUNDERWAFFE", "WUNDERWAFFEN", "WURST", "WURSTS", "ZEITGEBER", "ZEITGEBERS", "ZEITGEIST", "ZITTERBEWEGUNG", "ZITTERBEWEGUNGEN", "ZUGZWANG", "ZUGZWANGED", "ZUGZWANGING", "ZUGZWANGS", "ZWEIGELT", "ZWEIGELTS", "ZWEIHANDER", "ZWEIHANDERS", "ZWERGSPITZ", "ZWERGSPITZES", "ZWETSCHGENKUCHEN", "ZWIEBACK", "ZWIEBACKS", "ZWISCHENZUG", "ZWISCHENZUGS"];
function get_syl() {
  var syllable = document.getElementsByClassName("syllable")[0].innerHTML;
  return syllable;
}

function answer() {
  currentSyllable = get_syl();
  var words = [];
  if(currentSyllable != lastSyllable) {
    var word = "Can't find matching word!";
    for (var j = 0; j < dictionary.length; j++) {
      if (dictionary[j].toLowerCase().includes(currentSyllable)){
        words.push(dictionary[j]);
      }
    }
    var text = "    Words:\n  ";
    var len = Math.min(6, words.length);
    for (var j = 0; j < len; j++) {
    	// randomly choose a word in words
    	var index = Math.floor(Math.random() * (words.length - 1));
    	if (j < 3) {
    		text = text + words[index] + ",  ";
    		if (j == 2) text = text + "\n";
    	}
    	else {
    		if (j == len - 1) {
    			text = text + words[index];
    		}
    		else {
    			text = text + words[index] + ",  ";
    		}
    	}

    }
    document.getElementById("ans").innerText = text;
    lastSyllable = currentSyllable;
  }
}

function main() {
  chrome.runtime.onMessage.addListener(
    function(request, sender, sendResponse) {
      var syllable = document.getElementsByClassName("syllable")[0], syllableExists;
      if(typeof(syllable) == 'undefined' && syllable == null){
        syllableExists = false;
      } else {
        syllableExists = true;
      }
      if(syllableExists){
        const syllable = get_syl(), top = document.querySelector('.quickRules');
        if(document.getElementById("ans") == null){
          var ans = document.createElement("p");
          ans.id = "ans";
          top.append(ans);
        }
        hintInterval = setInterval(answer, 500);
      }
    }
  );
}

var hintInterval, toggle = true, currentSyllable, lastSyllable;

window.addEventListener("load", function () {
  main();
});
